# -*- coding: utf-8 -*-

EVENT_TYPE_START = "start"
EVENT_TYPE_PROGRESS = "progress"
EVENT_TYPE_PERFORMANCE = "performance"
EVENT_TYPE_END_HISTORY = "endHistory"
EVENT_TYPE_START_REALTIME = "startRealTime"
EVENT_TYPE_EVENT = "event"
EVENT_TYPE_SPAN = "span"
EVENT_TYPE_WARNING = "warning"
EVENT_TYPE_STOP = "stop"
EVENT_TYPE_DESTROY = "destroy"

UOM_KEY = "uom"
VALUE_KEY = "value"
TIMESTAMP_KEY = "timestamp"

DEFAULT_ANNOTATION_DURATION = 30000
